CONTIKI_PROJECT = sensingComponent
CONTIKI_SOURCEFILES += sensingComponent.c

TARGET=iotlab-m3

APPS += kevoree-runtime

all: $(CONTIKI_PROJECT)


CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
