CONTIKI_PROJECT = blinkComponent
CONTIKI_SOURCEFILES += blinkComponent.c

TARGET=iotlab-m3

APPS += kevoree-runtime

all: $(CONTIKI_PROJECT)


CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
