CONTIKI_PROJECT = SieveofEratosthenes
CONTIKI_SOURCEFILES += SieveofEratosthenes.c

TARGET=iotlab-m3

APPS += kevoree-runtime

all: $(CONTIKI_PROJECT)


CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
