CONTIKI_PROJECT = helloWorldComponent
CONTIKI_SOURCEFILES += helloWorldComponent.c

TARGET=iotlab-m3

APPS += kevoree-runtime

all: $(CONTIKI_PROJECT)


CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
